### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by wafer-li** [yudachi/plugin-expedition#1]
1、建议标记出当前选中的远征项目
肝晕了头之后就忘了选的是什么远征了

2、能否添加一些必要的计算功能？
例如【大发】和【大成功】对资源收益的影响
（最好能够检测舰队里的大发数量，难以实现的话，可以考虑通过添加大发数量的选择框来进行计算）

**Comment by malichan** [comment]
这个稍后加一下

**Comment by malichan** [comment]
1. 已经在v1.2.2里添加了
2. 考虑在下一个大版本添加
