### ISSUE TITLE
[3.0.1] undefined error

### ISSUE THREAD

**Issue by wafer-li** [yudachi/plugin-expedition#15]
Poi's version: poooi/poi@5fe9cc5036d93bf2f53601a89d6fe2c2c925c04f

![image](https://cloud.githubusercontent.com/assets/12459199/17426128/ce5e0454-5b0f-11e6-90bb-61ecfca36f75.png)

![image](https://cloud.githubusercontent.com/assets/12459199/17426139/f78681c6-5b0f-11e6-99d3-e9467714791d.png)

黑人问号.jpg

**Comment by ruiii** [comment]
@dkwingsmt

**Comment by dkwingsmt** [comment]
我这儿没法重现。你试试更新到刚发的3.0.2（修复了几个初始化错误）？再不行的话试试 `localStorage._storeCache = undefined; 0`  （别忘了 `;0`，不信的话你可以试试）

**Comment by wafer-li** [comment]
Fixed.
