### ISSUE TITLE
不能正確讀取遠征資訊

### ISSUE THREAD

**Issue by skipness** [yudachi/plugin-expedition#17]
不知道何時開始出現這個問題, 已經嘗試把poi整個去掉再安裝一次結果也是一樣
![default](https://cloud.githubusercontent.com/assets/8035517/18052619/f43f6e34-6e2d-11e6-9f2d-5c4ad6a303f0.PNG)

**Comment by KochiyaOcean** [comment]
明明提供了模板的说……请提供更详细的信息（版本啦报错信息什么的）

**Comment by SoraYama** [comment]
@skipness 不知道你的本体和插件版本是？

**Comment by skipness** [comment]
poi版本: 7.0.2
插件版本: 3.0.5
windows 10 64bit

![default](https://cloud.githubusercontent.com/assets/8035517/18053255/1dd344e8-6e31-11e6-9a75-1d7b612c6df2.PNG)

**Comment by dkwingsmt** [comment]
@skipness 去 %appdata%/poi 把 Local Storage 删了再试试吧

**Comment by skipness** [comment]
忘了說2, 6, 37, 38號遠征都會出現這個信息, 其他沒試過

**Comment by skipness** [comment]
> @skipness 去 %appdata%/poi 把 Local Storage 删了再试试吧

試過了, 還是一樣

**Comment by dkwingsmt** [comment]
@skipness 按一下 Ctrl-Shift-i 弹出 devtools，看一下有没有什么错误？另外在 console 中输入 getStore('ext.poi-plugin-expedition._.expeditions') 截图看看

**Comment by skipness** [comment]
> @skipness 按一下 Ctrl-Shift-i 弹出 devtools，看一下有没有什么错误？

![default](https://cloud.githubusercontent.com/assets/8035517/18053478/23106eb2-6e32-11e6-8b51-ed64fefc7ff0.PNG)

> 另外在 console 中输入 getStore('ext.poi-plugin-expedition._.expeditions') 截图看看

![default](https://cloud.githubusercontent.com/assets/8035517/18053461/0818f0fc-6e32-11e6-9406-3fc967e496a0.PNG)

**Comment by dkwingsmt** [comment]
这错误简直尴尬…… 怎么做到的……

**Comment by dkwingsmt** [comment]
试试这个呢？ console.log(require('lodash'), require('lodash').keyBy)

**Comment by skipness** [comment]
> 试试这个呢？ console.log(require('lodash'), require('lodash').keyBy)

![default](https://cloud.githubusercontent.com/assets/8035517/18053643/15304316-6e33-11e6-97f1-bd42d7e0115d.PNG)

**Comment by dkwingsmt** [comment]
唔…… 在设置-插件列表中，远程信息前面点一下那个暂停按钮，再点一下之后的播放按钮（重启动插件）会好吗？

**Comment by skipness** [comment]
依舊出同樣的信息
