### ISSUE TITLE
鼠标悬停时，信息显示错误

### ISSUE THREAD

**Issue by wafer-li** [yudachi/plugin-expedition#2]
版本：electron-v0.28.3-ia32
          poi master 分支
          commit SHA: 88bf50690b5611656acd8f5524fc2e58e3a908bf

平台：WIN7 X64 旗舰版

现象：鼠标悬停在远征收支的资源项时，只显示了一部分信息
如图
![qq 20150626074723](https://cloud.githubusercontent.com/assets/12459199/8367285/a0594992-1bd7-11e5-8998-fa909f4ba3ce.png)

**Comment by malichan** [comment]
呃，我一直用横版测试的……下个版本提示框的方向换一下吧

**Comment by wafer-li** [comment]
@malichan 
开发辛苦了，今天舰娘维护，新版本测试的话要等一阵子了
