### ISSUE TITLE
2裝母4驅逐跑15遠征會提示配置不對

### ISSUE THREAD

**Issue by dkwingsmt** [yudachi/plugin-expedition#5]
rt  

［其实我不知道应该对还是应该不对

**Comment by taroxd** [comment]
wiki上没提到装母（而MO作战提到了）。

等他跑回来就知道对不对咯……

**Comment by dkwingsmt** [comment]
我也专门为此查了下wiki……谜

**Comment by dkwingsmt** [comment]
![image](https://cloud.githubusercontent.com/assets/1596656/11166587/33d2898a-8b00-11e5-8acd-e2a9ef0d60b8.png)
信他？
