### ISSUE TITLE
i18n typo

### ISSUE THREAD

**Issue by wafer-li** [yudachi/plugin-expedition#8]
![qq 20151227130334](https://cloud.githubusercontent.com/assets/12459199/12008797/5aa4562c-ac9a-11e5-83a1-fb720651e96d.png)

**Comment by taroxd** [comment]
fixed in https://github.com/poooi/plugin-expedition/commit/cdd75328e54aad2d8052e8184250c9af4737add0

**Comment by wafer-li** [comment]
:joy: 嗯……希望 npm 新版本早日放出
